### ISSUE TITLE
Better Support for Aurora Tools.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal_galaxy#133] opened 2018-12-05 00:14 UTC
The PR #105 fixed some issues with Aurora Tools integration and CSS with the base Tripal site but there are still a few issues.  @MingChen0919 pointed out that collapsed trees are not collapsed when viewed in the Tripal site.  

@MingChen0919 provided the following image to demonstrate the problem.

<img width="942" alt="screen shot 2018-11-30 at 9 52 24 pm" src="https://user-images.githubusercontent.com/1262709/49323493-575c6e00-f4ea-11e8-88a6-4decd6489e66.png">

**Comment by MingChen0919** [comment] 2018-12-05 14:52
I noticed that this might not be a Tripal Galaxy issue. This might be caused by conflicts between javascript libraries in Galaxy and Aurora Tools.

**Comment by spficklin** [comment] 2018-12-05 18:19
Oh, is Aurora Tools relying on Galaxy CSS/JS?

**Comment by MingChen0919** [comment] 2018-12-05 19:45
No, it turned out that it was purely a Aurora Tool issue. The issue appears when some R packages are used. I don't know much about JS, but @almasaeed2010 helped me fix the JS problem. I am going to close this issue.

**Closed as completed by MingChen0919** 2018-12-05 19:45 UTC

**Comment by spficklin** [comment] 2018-12-05 21:19
Great. Thanks!
