### ISSUE TITLE
Uncaught exception in exposed API method

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#99] opened 2018-05-30 16:34 UTC
I submitted a workflow through the Tripal web interface, invoked it using `drush`, and got the following error message:
```
$ drush trp-galaxy-invoke --submission=15
Launching workflow...
Uploading OA.vcf...
Done.
Uncaught exception in exposed API method:                                                                                                                   [error]
```
In the `job queue` of the Tripal web interface, the job has the `Error` status.

Another user with admin privileges on the Galaxy server, was able to run the workflow successfully.

**Comment by spficklin** [comment] 2018-05-31 22:31
Hi Nic.  I think that is a Galaxy API error.  Can you provide the code you used to submit the workflow?

**Comment by spficklin** [comment] 2018-05-31 22:32
Just to add more... it's not a blend4php error, but these errors usually occur when an improper array of info is provided.

**Comment by NicHerndon** [comment] 2018-05-31 22:51
Thank you for looking into this.

I went through the steps of the workflow on the Tripal side, and then attempted to run it using drush, as shown in the attached screenshots.

![screen shot 2018-05-31 at 6 45 32 pm](https://user-images.githubusercontent.com/4636279/40843400-d9e3eed0-657e-11e8-99a1-0219dddff715.png)
![screen shot 2018-05-31 at 6 47 05 pm](https://user-images.githubusercontent.com/4636279/40843401-d9edc87e-657e-11e8-8526-ba51e296e64d.png)
![screen shot 2018-05-31 at 6 47 26 pm](https://user-images.githubusercontent.com/4636279/40843402-d9f8ac1c-657e-11e8-8e52-450536ab591e.png)
![screen shot 2018-05-31 at 6 47 49 pm](https://user-images.githubusercontent.com/4636279/40843403-da028890-657e-11e8-8244-f8b09a111e83.png)
![screen shot 2018-05-31 at 6 49 00 pm](https://user-images.githubusercontent.com/4636279/40843404-da0de0dc-657e-11e8-9124-41eab7489c13.png)

**Comment by spficklin** [comment] 2018-06-01 16:46
Can you share your Galaxy workflow .ga file and a sample data file that we can test?

**Comment by NicHerndon** [comment] 2018-06-01 17:25
[workflow_and_sample.zip](https://github.com/tripal/tripal_galaxy/files/2063599/workflow_and_sample.zip)

**Comment by spficklin** [comment] 2018-06-07 02:46
Hi @NicHerndon .  I have dug as deep into this problem as a I can and I have posted an issue on the Galaxy Project galaxyproject/galaxy#6299.   Take a look at that issue to get more info.

**Comment by spficklin** [comment] 2018-06-07 02:48
I have also updated blend4php so it can give you those errors when there's problems. So that should help a bit more with debugging.  Just pull the most recent code of blend4php.

**Comment by NicHerndon** [comment] 2018-07-01 17:56
@spficklin, got a patch from Galaxy, the job no longer fails, but after it finishes in Galaxy, Tripal seems unaware that the job finished and keeps reporting the status of the job as `Submitted`.

**Comment by NicHerndon** [comment] 2018-07-01 18:40
@shawnawsu, below are the steps to reproduce this problem:

1. Go to `admin/tripal/extension/galaxy/workflows`.
2. Click on a workflow to run.
3. Go through the steps of the workflow and provide the data/files it needs, then click `Submit`.
4. Copy the execute command, in this case `drush trp-run-jobs --username=nic.herndon@uconn.edu --root=/var/www/Drupal`, log into the web server, change into the Drupal directory, paste the command and execute it.
5. After the job completes on Galaxy, Tripal still lists it as `Submitted`, on `admin/tripal/extension/galaxy/job-queue` page.

**Comment by shawnawsu** [comment] 2018-07-16 10:18
Hi @NicHerndon,

After spending lots of time debugging this it appears to be a shortcoming in the tripal galaxy module's ability to handle single-step workflows. I was able to successfully run the workflow when I added the first step of input dataset and then connected it to the 'aurora_genotype_matrix' step, like the attached image of the workflow. 
![screen shot 2018-07-16 at 6 03 07 am](https://user-images.githubusercontent.com/24374002/42753164-00ffbf5a-88be-11e8-9a4b-2c0d12f6d5e3.png)

You can see here in my tripal galaxy that the workflow ran successfully:
![screen shot 2018-07-16 at 6 12 14 am](https://user-images.githubusercontent.com/24374002/42753613-785467a8-88bf-11e8-97fa-0b54ef0daa4b.png)
<img width="1315" alt="screen shot 2018-07-16 at 6 13 28 am" src="https://user-images.githubusercontent.com/24374002/42753615-7a6c468c-88bf-11e8-9439-cda5d32c7573.png">

While we ( @spficklin ) try and figure out why one step workflows won't work with tripal galaxy you can get past this roadblock by adding the simple data input step. 

Given the problem is no longer the exposed API method issue I am going to close out this ticket and open a new one for the single-step workflow issue.

Let me know if you have any question or suggestions.

Thanks,
Shawna

**Comment by NicHerndon** [comment] 2018-07-16 13:58
Thank you Shawna. I updated the workflow and I was able to run it with drush. After the workflow completed running, I checked the status at admin/tripal/extension/galaxy/workflows/report/%. It displays, Currently, no results exist for this job. The current state of the job is: Submitted. Do I need to create a new issue for this?

On Jul 16, 2018, at 6:18 AM, Shawna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @NicHerndon<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNicHerndon&data=02%7C01%7Cnic.herndon%40uconn.edu%7C90cb9f73b8284806ae9108d5eb057cc8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636673331155259699&sdata=SqEXguSu0aiODNxloZGB6aoYYBTj7%2BH3lGEHi97fKqA%3D&reserved=0>,

After spending lots of time debugging this it appears to be a shortcoming in the tripal galaxy module's ability to handle single-step workflows. I was able to successfully run the workflow when I added the first step of input dataset and then connected it to the 'aurora_genotype_matrix' step, like the attached image of the workflow.
[screen shot 2018-07-16 at 6 03 07 am]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374002%2F42753164-00ffbf5a-88be-11e8-9a4b-2c0d12f6d5e3.png&data=02%7C01%7Cnic.herndon%40uconn.edu%7C90cb9f73b8284806ae9108d5eb057cc8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636673331155259699&sdata=pMn13jwdCFoHngjzEloCsfXBcgiMWQ%2Fl5mP029JCoak%3D&reserved=0>

You can see here in my tripal galaxy that the workflow ran successfully:
[screen shot 2018-07-16 at 6 12 14 am]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374002%2F42753613-785467a8-88bf-11e8-97fa-0b54ef0daa4b.png&data=02%7C01%7Cnic.herndon%40uconn.edu%7C90cb9f73b8284806ae9108d5eb057cc8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636673331155269709&sdata=b3cUH7ql%2BNp8J%2B3pG66q6EUW3anR%2FV%2F%2BohpkcrqUYTs%3D&reserved=0>
[screen shot 2018-07-16 at 6 13 28 am]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F24374002%2F42753615-7a6c468c-88bf-11e8-9439-cda5d32c7573.png&data=02%7C01%7Cnic.herndon%40uconn.edu%7C90cb9f73b8284806ae9108d5eb057cc8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636673331155269709&sdata=14hJ4XpTTPJjFyIIpOg1vFjW4Kkwsy9Y7%2BUzV3rz0VQ%3D&reserved=0>

While we ( @spficklin<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspficklin&data=02%7C01%7Cnic.herndon%40uconn.edu%7C90cb9f73b8284806ae9108d5eb057cc8%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636673331155279714&sdata=rAtIDo2h5KPHbJpDbpYf41E7CoLU5aMwJjeiYAS4DCY%3D&reserved=0> ) try and figure out why one step workflows won't work with tripal galaxy you can get past this roadblock by adding the simple data input step.

Given the problem is no longer the exposed API method issue I am going to close out this ticket and open a new one for the single-step workflow issue.

Let me know if you have any question or suggestions.

Thanks,
Shawna

**Comment by shawnawsu** [comment] 2018-07-16 14:09
A job to check the status of each job will be created on the next cron run and execute the next time an admin runs tripal jobs. I'm not entirely sure what the desired behavior for the status checking is, @spficklin what's is the correct flow for this? You can run the trp-galaxy-status drush call to get it to update the tripal status of the job: `drush trp-galaxy-status --submission=#** --force=true`
** Should be the submission id of the job.

**Comment by shawnawsu** [comment] 2018-10-03 17:47
@NicHerndon Is this still a problem?

**Comment by spficklin** [comment] 2018-12-06 23:02
I'm fairly certain this is fixed so I'm closing.  If it's not please comment and we'll reopen it.

**Closed as completed by spficklin** 2018-12-06 23:02 UTC
Labels: help wanted
