### ISSUE TITLE
Workflow status not updated properly when workflow is changed on galaxy side

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#15] opened 2017-07-18 18:06 UTC

**Comment by cwytko** [comment] 2017-07-18 18:41
Found this issue while checking the workflow tables on a join for the file_usage column of the table for users to see what files they have uploaded and where they are being used (if at all)

**Comment by spficklin** [comment] 2017-09-11 05:38
It's not clear what this issue is.  Can you give more details?

**Comment by spficklin** [comment] 2017-09-22 15:57
I think this is duplicate of issue #24 .  Marking closed unless you can provide further details.

**Closed as completed by spficklin** 2017-09-22 15:57 UTC
Labels: bug
