### ISSUE TITLE
Galaxy User Permissions Broken

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#48] opened 2018-01-10 18:39 UTC
By default, admins have permission to execute workflows and to admin the Galaxy module but these check marks do not show up on the tripal permissions page. (IE Galaxy module exposes two permissions items, "Execute Published Galaxy Workflows" and "Administer Galaxy". By default admins can do both, but no check marks show up on permission page)

By default, anonymous and authenticated users can also try to run Galaxy workflows (even without having that permission in the drupal permissions) BUT they can't upload files.

If I add "Execute Published Galaxy Workflows" as a permission for authenticated users, the behavior remains the same. An authenticated user can still see the workflows and try to run them but still cannot upload files.

I think the expected behavior would be that if the "Execute Published Galaxy Workflows" is NOT checked for a role, a user with that role would not be able to start a workflow (which would mean they also would not be able to upload files or even get to the page where that is possible).

**Comment by spficklin** [comment] 2018-02-11 09:15
Hi @mestato 

In your first paragraph, do you mean you would expect that permissions should be automatically set for anonymous and authenticated users when the module is installed?

To allow anonymous/authenticated users to upload files you have to check the 'Upload Files' permission under the Tripal section.  I don't think this has actually been tested for anonymous users, so it may cause problems because anonymous users are all going to share the same user ID and the Tripal file upload code stores files by user ID. We probably need to update that code to handle anonymous users differently. 

But, I think if you turn on that "Upload Files" permission you'll get more expected behavior.

**Comment by almasaeed2010** [comment] 2018-02-14 18:52
Hi,

If I understood correctly, the `use galaxy` permission isn't getting applied on the webform nodes. I implemented a fix in #70 to detect the node type and if it is part of galaxy workflows then checks what the `user_access('use galaxy')` function returns and allows or denies access based on that. This way we have a custom access control for tripal galaxy workflow forms.

The file upload issue, as Stephen mentioned, is fixed using the Tripal permissions.

Thanks!

**Comment by MingChen0919** [comment] 2018-02-20 01:23
just want to confirm that this fix has been tested and it worked. I found another permission related issue #71

**Comment by MingChen0919** [comment] 2018-02-20 03:09
#71 is fixed in PR #72

**Closed as completed** 2018-03-14 13:22 UTC
Labels: bug, release-blocker, waiting on submitter
