### ISSUE TITLE
A webform field that allows for uploading all types of files is needed

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#26] opened 2017-09-29 14:37 UTC
Some galaxy tools have "data" type input that does not specify any input format (allowed file types). This type of inputs is supposed to accept all kinds of files. In Tripal webforms, this type of inputs only allows for uploading files with `.data` extension. 

The code below is from a Galaxy tool, the "data" type param does not have a `format` attribute, which means it should accept all kinds of format.

```

    <inputs>
        <param type="data" name="file_list" multiple="true" />
        <param type="text" name="format" label="the format of input files (e.g., fastq, fastqsanger, fasta)"/>
```

**Comment by spficklin** [comment] 2017-09-29 19:16
Okay, thanks... we'll get this fixed.

**Comment by spficklin** [comment] 2017-09-30 14:50
Can you point to an example workflow that has a tool with this situation?

**Comment by MingChen0919** [comment] 2017-09-30 14:55
workflow `quality-control-se-v2`: https://galaxy.bioinfo.wsu.edu/u/mingchen0919/w/quality-control-se-v2

**Comment by spficklin** [comment] 2017-10-16 07:00
So, looking at this workflow, in the tool setup, the extension value is set to 'data'.  This is why the webform in Tripal requires files with a .data extension.   There is no hard-coded  'data' extension in the Tripal Galaxy module.  I did have to make a fix to the uploader when no file extensions are provided and that fix is in the most recent development version of Tripal (posted this weekend).  But despite the fix, this problem you describe still remains because the tool input has the 'extension' element set to 'data'.

Also, Tripal only recognizes two types of data inputs (i.e. where files are provided):  'data_input' and 'data_collection_input'.  This tool's first input has a type of 'data'.  For Tripal, when it sees this 'data' type it expects that the data already exists in the history but since it doesn't it winds up providing the uploader in the form anyway.    But you're not getting the collection list uploader like you want.  To fix both issues, I think you may need to change the first input type to 'data_collection_input', and change the 'extensions' on that input to remove the 'data'.

**Comment by cwytko** [comment] 2017-10-17 18:32
@MingChen0919  Please check this when you have time :smile:

**Comment by cwytko** [comment] 2017-10-17 23:38
Wait for confirmation from the Ming :stuck_out_tongue:

**Comment by MingChen0919** [comment] 2017-10-18 02:41
It won't allow me to upload files. I got this message:

<img width="505" alt="screen shot 2017-10-17 at 10 40 37 pm" src="https://user-images.githubusercontent.com/1262709/31698612-51359d6c-b38c-11e7-85da-ff921f5b7ce2.png">

**Comment by spficklin** [comment] 2017-10-18 03:44
Hi @MingChen0910 I think the problem is with the workflow and not with the Tripal code. Does my comment above make sense?

**Comment by MingChen0919** [comment] 2017-10-18 12:55
Hi @spficklin, your comment makes sense. However, the reason that I created this tool is that I needed a galaxy tool that can function as an 'adapter'. This adapter takes a dynamic number of inputs and converts it to a dataset collection. A lot of galaxy tools don't output a dataset collection, for example, the trimmomatic tool can output any number of files. This tool can build a dataset collection or paired dataset collection and pipe it to other tools like hisat. If I change the input type to `data_collection_input` and specify an `extension`, then this tool won't do what I needed. This tool works as expected in galaxy. Since it works in galaxy, my understanding is that there should be a way that makes it also work with the Tripal Galaxy module. This tool does not need a `collection list uploader`, actually it should not be. It just needs a regular file uploader which allows any types of files being uploaded and transferred to galaxy.

**Comment by spficklin** [comment] 2017-10-18 15:33
I'm not sure I understand... But first question do you have to have 'data' in the tools 'extensions' parameter? If you take that out it will solve one of the problems.

**Comment by MingChen0919** [comment] 2017-10-18 16:28
so, in a galaxy tool config file, 'data' is a value for the `type` attribute, the extensions you are talking about is specified by another attribute called `format`. Taking out 'data' will change the input type but not the allowed extensions. The allowed extensions are specified by the attribute `format`. See this page: https://docs.galaxyproject.org/en/latest/dev/schema.html#data and here: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param for available values of attribute `type`

However, the `format` attribute is optional. It can be empty. When it is empty, it seems the tripal galaxy module uses the value from the attribute `type` as allowed extensions.

**Comment by spficklin** [comment] 2017-10-18 17:01
Tripal Galaxy module only pulls the allowed extension from the 'extensions' list for an input. Here's the JSON array returned by Galaxy for the tool.  Note the 'data' element in the 'extensions' list of the first input.  It's not pulling it from the type.  The word 'data' is in the 'extensions' list.  If you can get that out then the uploader will allow files of any type...

```
{
    "action": "/tool_runner/index",
    "biostar_url": null,
    "citations": false,
    "description": "Create a list of datasets collection from files in history.",
    "display": true,
    "edam_operations": [ ],
    "edam_topics": [ ],
    "enctype": "application/x-www-form-urlencoded",
    "errors": { },
    "form_style": "regular",
    "help": "",
    "history_id": "a89326c04f05a73f",
    "id": "toolshed.g2.bx.psu.edu/repos/mingchen0919/rmarkdown_collection_builder/rmarkdown_collection_list/1.0.0",
    "inputs": {
        "0": {
            "argument": null,
            "edam": {... },
            "extensions": [
                "data"
            ],
            "help": "",
            "hidden": false,
            "is_dynamic": false,
            "label": "",
            "max": null,
            "min": null,
            "model_class": "DataToolParameter",
            "multiple": true,
            "name": "file_list",
            "optional": false,
            "options": { ... },
            "refresh_on_change": true,
            "text_value": "No dataset.",
            "type": "data",
            "value": {
                "values": [
                    {
                        "id": "293169b6d64514e5",
                        "src": "hda"
                    }
                ]
            }
        },
        "1": {... },
        "2": {...}
    },
    "job_id": null,
    "job_remap": false,
    "labels": [ ],
    "message": "",
    "method": "post",
    "model_class": "Tool",
    "name": "Collection type (list)",
    "panel_section_id": "rmarkdown_tools",
    "panel_section_name": "R markdown tools",
    "requirements": [... ],
    "sharable_url": "https://toolshed.g2.bx.psu.edu/view/mingchen0919/rmarkdown_collection_builder",
    "state_inputs": {...},
    "tool_shed_repository": {...},
    "version": "1.0.0",
    "versions": [
        "1.0.0"
    ],
    "warnings": ""
}
```

**Comment by spficklin** [comment] 2018-02-11 10:09
I think this issue has been resolved.  If not, please comment and we can reopen.

**Closed as completed by spficklin** 2018-02-11 10:09 UTC
Labels: bug
