### ISSUE TITLE
Workflow jobs just uploaded files and stop

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal_galaxy#147] opened 2019-07-18 01:58 UTC
Hi,

I have tried to run a workflow through tripal_galaxy Automatic Webform Creation. The workflow looks like this:

![image](https://user-images.githubusercontent.com/14274330/61423255-b5d34100-a941-11e9-9fbe-21576e6a797d.png)

And after submit the job in tripal, I mannually run the job and get this information:

![image](https://user-images.githubusercontent.com/14274330/61423461-76592480-a942-11e9-9063-c96483476160.png)

It seems that the job just uploaded two files and stop, and nothing passed to galaxy because there are no history record in the galaxy server. And the job status kept as "submitted".

Did I miss something?

Any suggestions would be appreciated.

Thank you.

SongtaoGui

**Comment by spficklin** [comment] 2019-07-18 02:28
Hi @songtaogui .  Thanks for posting the issue!   A few questions for you.  
1)  What version of Tripal are you using (v2 or v3)?  
2)  Could you export your workflow and post it here so I can import it on my end and test it?  
3) What is the version of the Galaxy server you are using?  You can find this out easily by going to the Tripal Galaxy admin page and clicking on the 'test' link next to the server. It should report if the connection was successful as well as the version of the Galaxy server.

**Comment by songtaogui** [comment] 2019-07-18 02:35
Hi @spficklin Thank you for your kind reply.

1. I am using Tripal v3.1
2. Please find the workflow in the file below (.txt sufix was added for uploading to github):
[Galaxy-Workflow-blast-protein-sequences_(imported_from_uploaded_file).ga`.txt`](https://github.com/tripal/tripal_galaxy/files/3404498/Galaxy-Workflow-blast-protein-sequences_.imported_from_uploaded_file.ga.txt)
3. The test output was `Successful connection to the Galaxy server (version 18.05)`

Thank you

**Comment by spficklin** [comment] 2019-07-18 15:51
Hi @songtaogui thanks for the info. I'm currently traveling but as soon as I can get some time I'll test things and see if  I can reproduce the problem you're experiencing.

**Comment by songtaogui** [comment] 2019-07-19 09:23
Hi, @spficklin. Thank you

This problem was because I didn't set the auto run of `trp-galaxy-status`, and I was wrong about `"nothing passed to galaxy because there are no history record in the galaxy server"` before, the job did passed to galaxy server and I didn't find it out.  Sorry about that.

However, there are other questions: 

1. When running workflows, the `Upload File` step could only be performed through administrator account. Trying with other user account showed a `Forbidden` alert:
![image](https://user-images.githubusercontent.com/14274330/61523595-43e51f80-aa47-11e9-9c74-858aa8841a7a.png)

I have tried to open both the `Execute` and `Admin` permission to authorized user and still only admin can upload files.

2. Normal Users can view all the workflow status that other account ( in my situation, the administrator account ) has ran before on their account page: 

> as showed in the picture, a normal user ( user 34 here), which haven't run any workflow yet, can see the workflow status of other users ( user 1 here )
![image](https://user-images.githubusercontent.com/14274330/61524507-2913aa80-aa49-11e9-9e44-bbc4d099d0c0.png)

3. In Galaxy, workflow can output only result from certain steps and hide others. But in tripal_galaxy, when a workflow completed, the output of each step, including the uploading step, were displayed. Is it possible to get only the output marked as `*` ?

Thank you !

Best wishes

**Comment by spficklin** [comment] 2019-07-20 03:51
Hi @songtaogui 

1) There are no controls within the Tripal Galaxy module that would limit uploads to just admin users.  So, there must be something else inhibiting those uploads.  Have you looked at the file management documentation for Tripal:  https://tripal.readthedocs.io/en/latest/user_guide/file_management.html

2) This is a bug!  I have just updated the code to fix this.  Can you pull the most recent version of the module from GitHub, clear the Drupal cache using `drush cc all` and then see if the problem is fixed?

3) I don't understand what you want in item 3 from above.  What do you mean "output marked as `*`"?

**Comment by songtaogui** [comment] 2019-07-22 03:30
Hi, @spficklin 
Thank you for the help.

For iterm 3 above:
In galaxy, you could control the outputs by turn on/off the asterisk button of a step, so that we can output only the result we want, rather than all the intermediates: 

![image](https://user-images.githubusercontent.com/14274330/61600712-a23b1980-ac64-11e9-97c3-742a79a0ffc7.png)

But in tripal_galaxy, when finish a workflow, the output page collects outputs of each step, whether or not the astersik button in the galaxy workflow were turned on:

![image](https://user-images.githubusercontent.com/14274330/61604191-17ade680-ac73-11e9-83c0-db03244cb7f0.png)

 I was wondering that is there a way to let tripal_galaxy collects only the output of the astersik marked step in galaxy ?

And another small question: the result of the input file (step 1) has a `Peek at the results` info, while the output file (step 2) hasn't: 
 
> step1
![image](https://user-images.githubusercontent.com/14274330/61604328-aa4e8580-ac73-11e9-81b3-858ef5abcec5.png)
step2
![image](https://user-images.githubusercontent.com/14274330/61604340-b5091a80-ac73-11e9-8a08-743cfdd488a9.png)

Is this because of the file suffix ?

Thank you

**Comment by spficklin** [comment] 2019-07-22 14:11
Oh, I understand now.  Yes, I think we can accommodate that.   We'll work on it.  In the meantime.  Did the update I applied for item #2 fix that problem and were you able to figure out the uploading problems?

**Comment by spficklin** [comment] 2019-07-29 13:44
Hi @songtaogui.  Just checking in about the answers to the other questions I asked?

**Comment by songtaogui** [comment] 2019-07-30 07:20
@spficklin 
sorry for the late reply.

I have just tried your uploaded code, and Yes! It works, thank you.

And the uploading problem was also solved by opening several tripal file management permissions.

Thank you again for your kindly help.

**Comment by spficklin** [comment] 2019-11-10 09:53
Hi @songtaogui 

I just committed a fix that will hide result files if they are not indicated as being part of the final files.   In the process, the results page has been simplified a bit.  For any new workflow submissions, the uploaded files won't show up on the results page either... only the final results.  Uploaded files will still show up on older submissions.  

It's been so long since you asked for this, I'm going to close this issue out as resolved.  But, if you still have issues please comment and I can reopen it.

**Closed as completed by spficklin** 2019-11-10 09:53 UTC
