### ISSUE TITLE
Link error on My Galaxy Workflows page

### ISSUE THREAD

**Issue by patricksis** [tripal/tripal_galaxy#146] opened 2019-05-24 16:59 UTC
Hello,
When viewing the submission on a specific workflow in the Galaxy workflow page, a error shows up 
```The requested page "/node/2038611/submission/82" could not be found.```
The submission page can be found using other methods, so this issue may be do to a link error.

### System information
Drupal Version: 7.67
Tripal Version: 3.0

**Comment by spficklin** [comment] 2019-05-24 18:12
Hi @patricksis thanks for reporting the issue.  Can you post a screenshot so we know where to look for this?

**Comment by patricksis** [comment] 2019-05-24 18:47
![InkedScreen Shot 2019-05-24 at 12 31 25 PM_LI](https://user-images.githubusercontent.com/38140425/58350024-cf20ab00-7e32-11e9-93f7-495a03f78a17.jpg)
The link circled is the one in question

**Comment by patricksis** [comment] 2019-05-29 18:39
The results page can be reached, it can be found here:https://hardwoodgenomics.org/user/2038611/galaxy-jobs/82

**Comment by mestato** [comment] 2019-05-29 20:03
Turns out the fastq-groomer has been running for 122 hours. So its Galaxy thing, not a Tripal Galaxy thing.

**Comment by spficklin** [comment] 2019-05-29 21:44
Perhaps we need to adjust the links so they do not appear if the job hasn't finished yet?

**Comment by mestato** [comment] 2019-05-29 22:14
I think it would suffice to change "submitted" to "running", which is a bit clearer. Just because it was successfully submitted, that doesn't give the user much confidence in what is now happening with it.

**Comment by spficklin** [comment] 2019-10-12 21:45
I'm not able to reproduce this problem.  If I run a job and the status is 'Submitted' I do see the 'View Submission' link but I do not see the error message.  Are you all still having this problem?

**Comment by spficklin** [comment] 2019-11-10 09:56
Closing for lack of comment. If you are still having the issue please respond.  There have been some updates to the code, so if you can pull it and test it out, it could be resolved.  

I did fix a bug in one of the more recent commits where webforms were incorrectly getting deleted but not the job.  Perhaps that was the source of the problem.  If you still have issues please comment.

**Closed as completed by spficklin** 2019-11-10 09:56 UTC
Labels: waiting on submitter
