### ISSUE TITLE
Get rid of duplicate files uploaded to Galaxy

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#45] opened 2018-01-10 18:31 UTC
When Tripal uploads file for a workflow to galaxy, have that file be stored in the data library partition of galaxy such that when a user is running a workflow and wants to use the same file, query the data library of that user on the galaxy side and provide the list of files previously uploaded to galaxy.

**Comment by spficklin** [comment] 2018-02-11 09:22
Duplicate of #31

**Closed as completed by spficklin** 2018-02-11 09:22 UTC
Labels: duplicate, File Issue
